steps:
  - command: 'bazel build -- //... \$(bazel query //... | grep -e "_container\$" -e "_container_push\$" -e "_layer" | while read target; do echo -\$target; done)'
    label: 'FreeBSD'
    agents:
    - "os=freebsd"
  - command: 'bazel build -- //... \$(bazel query //... | grep -e "_container\$" -e "_container_push\$" -e "_layer" | while read target; do echo -\$target; done)'
    label: 'macOS'
    agents:
    - "os=darwin"
  - command: 'bazel run @com_github_buildbarn_bb_deployments//ci:run-ci'
    label: 'Linux'
    agents:
    - "os=linux"
